### PR TITLE
changed wordpress_sites variable to app_config

### PR DESCRIPTION
**Pull request by nathanielks**

### CODE REVIEW

**Comment by nathanielks** [comment]
@swalkinshaw want me to update the `wordpress-install` and `wordpress-setup` roles to be `app-install` and `app-setup`?

**Comment by austinpray** [comment]
Yes

**Comment by austinpray** [comment]
Wait actually hold on

**Comment by nathanielks** [comment]
giphy-14

**Comment by swalkinshaw** [comment]
This will require some more thought since there's way more WP specific things in this project.

**Comment by swalkinshaw** [comment]
@nathanielks I don't really know how to deal with this right now since it involves a lot of other things so I'm gonna punt on it for now :(

**Pull request closed without merging**
