### PR TITLE
Add information on how to deploy with the git strategy.

### LINKED ISSUE #201: Clarify deployment workflow
Hello!
Would it be possible to explain de deployment process a bit more? Does this line: https://github.com/roots/bedrock-ansible/blob/master/group_vars/production#L8 should be replaced by my Bedrock Wordpress project? does it deploy from git or from local code? How do we deal with deploying from specific branch? We normally have a `develop`, a `staging` and a `production` branch. how do I match thoses with the environments?

Thanks!!!

### PR DESCRIPTION
**Pull request by louim**
I added some information to the readme and changed `branch` to `project.branch`. Let me know if anything is missing or if there's anything you want me to improve. This should fix #201

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Wondering if we should just set `branch` by default in staging and production (to `staging` and `master` respectively)?

**Comment by louim** [comment]
@swalkinshaw do you mean in the config files (explicitely) or in the deploy role (implicitely)? What about develop then?

**Comment by swalkinshaw** [comment]
I meant in the group var files explicitly. Just so it's visible and people know. We go by the assumption that you're using Vagrant for dev and not deploying so develop wouldn't apply then?

**Comment by louim** [comment]
That's fine by me, I think it will be more obvious to people if it's written in the config when they start a new project. Do you want me to update te pull request?

**Comment by swalkinshaw** [comment]
Sure :+1:

**Comment by swalkinshaw** [comment]
@louim I think the other changes still apply though as well. I'm nitpicking but can you fix the casing on "git" and "Wordpress" to "Git" and "WordPress" as well please? :)

**Comment by austinpray** [comment]
Why would you assume the person has a "Staging" branch?

**Comment by swalkinshaw** [comment]
@austinpray I don't really. That's why it's explicit so it's easy to customize in there. We could just default to `master` in there as well?

**Comment by austinpray** [comment]
Yeah default to master 👍🏻

**Comment by louim** [comment]
Done!

**Comment by louim** [comment]
Hold on, Ill squash those commits together.

**Comment by swalkinshaw** [comment]
Thanks!

**Pull request merged**
