### PR TITLE
Add SMTP role

### PR DESCRIPTION
**Pull request by swalkinshaw**
Ref #122

This uses ssmtp as a simple mail delivery tool for forwarding mail to an external SMTP server.

/cc @austinpray @nathanielks @rstormsf

### CODE REVIEW

**Comment by austinpray** [comment]
Gonna try this out on one of my servers to test

**Comment by swalkinshaw** [comment]
Closing this. Realized this solution isn't enough since email should work out of the box on development too without requiring a 3rd party SMTP service.

**Comment by swalkinshaw** [comment]
and we're back! Going to stick with as anyone can use their Gmail (for example) in development.

**Comment by austinpray** [comment]
:sunglasses:

**Comment by rstormsf** [comment]
:+1:

**Pull request merged**
